platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!
use_frameworks!

target 'TestAWS' do
	pod 'AWSS3'

end

post_install do |installer|
  # This removes the warning about swift conversion, hopefuly forever!
  installer.pods_project.root_object.attributes['LastSwiftMigration'] = 9999
  installer.pods_project.root_object.attributes['LastSwiftUpdateCheck'] = 9999
  installer.pods_project.root_object.attributes['LastUpgradeCheck'] = 9999
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
         config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
         config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
         config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
     end
  end
end
